### ISSUE TITLE
Python 2 & Python 3 : KeyError: 'cas:attributes'

### ISSUE THREAD

**Issue by jhautefeuille** [cameronbwhite/Flask-CAS#31]
@app.route('/')
@login_required
def root():
	return render_template('index.html', username=cas.username, display_name=cas.attributes['cas:displayName'])

if __name__ == "__main__":
	app.run(host='0.0.0.0', debug=True)

Produces

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.4/dist-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/usr/local/lib/python3.4/dist-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.4/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.4/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.4/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.4/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.4/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.4/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.4/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.4/dist-packages/flask_cas/routing.py", line 45, in login
    if validate(flask.session[cas_token_session_key]):
  File "/usr/local/lib/python3.4/dist-packages/flask_cas/routing.py", line 125, in validate
    attributes = xml_from_dict["cas:attributes"]
KeyError: 'cas:attributes'

**Comment by jhautefeuille** [comment]
Issue is not fixed...Same error message.

**Comment by cameronbwhite** [comment]
Ok thanks. Can you prove it. Please show the error in full and the version of Flask-CAS.

**Comment by jhautefeuille** [comment]
Update
------

sudo pip install -U Flask-CAS
sudo pip3 install -U Flask-CAS

Version
-------

Python 3.4.3 (default, Oct 14 2015, 20:28:29) 
[GCC 4.8.4] on linux

Python 2.7.6 (default, Jun 22 2015, 17:58:13) 
[GCC 4.8.2] on linux2

Code
----

@app.route('/')
@login_required
def root():
	return render_template('index.html', username=cas.username, display_name=cas.attributes['cas:displayName'])

Run
---
# python3.4 main.py 
 * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
 * Restarting with stat
 * Debugger is active!
 * Debugger pin code: 495-586-768

Error
-----

127.0.0.1 - - [20/Jan/2016 14:47:18] "GET / HTTP/1.1" 302 -
--------------------------------------------------------------------------------
DEBUG in routing [/usr/local/lib/python3.4/dist-packages/flask_cas/routing.py:54]:
Redirecting to: https://sso.instep.fr/cas?service=http%3A%2F%2Flocalhost%3A5000%2Flogin%2F
--------------------------------------------------------------------------------
127.0.0.1 - - [20/Jan/2016 14:47:18] "GET /login/ HTTP/1.1" 302 -
--------------------------------------------------------------------------------
DEBUG in routing [/usr/local/lib/python3.4/dist-packages/flask_cas/routing.py:100]:
validating token ST-55140-AccCBuj6nPyJKo9gCvJu-sso.instep.fr
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
DEBUG in routing [/usr/local/lib/python3.4/dist-packages/flask_cas/routing.py:109]:
Making GET request to https://sso.instep.fr/cas/serviceValidate?service=http%3A%2F%2Flocalhost%3A5000%2Flogin%2F&ticket=ST-55140-AccCBuj6nPyJKo9gCvJu-sso.instep.fr
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
DEBUG in routing [/usr/local/lib/python3.4/dist-packages/flask_cas/routing.py:122]:
valid
--------------------------------------------------------------------------------
127.0.0.1 - - [20/Jan/2016 14:47:21] "GET /login/?ticket=ST-55140-AccCBuj6nPyJKo9gCvJu-sso.instep.fr HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.4/dist-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/usr/local/lib/python3.4/dist-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.4/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.4/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.4/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.4/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.4/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.4/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.4/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.4/dist-packages/flask_cas/routing.py", line 45, in login
    if validate(flask.session[cas_token_session_key]):
  File "/usr/local/lib/python3.4/dist-packages/flask_cas/routing.py", line 125, in validate
    attributes = xml_from_dict["cas:attributes"]
KeyError: 'cas:attributes'
127.0.0.1 - - [20/Jan/2016 14:47:21] "GET /login/?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
127.0.0.1 - - [20/Jan/2016 14:47:21] "GET /login/?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
127.0.0.1 - - [20/Jan/2016 14:47:21] "GET /login/?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
127.0.0.1 - - [20/Jan/2016 14:47:21] "GET /login/?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
127.0.0.1 - - [20/Jan/2016 14:47:21] "GET /login/?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -

**Comment by andyxning** [comment]
I run into this problem also. I seems that we may change `attributes = xml_from_dict["cas:attributes"]` to `attributes = xml_from_dict.get("cas:attributes", OrderedDict())` to fix the **KeyError**.

**Comment by andyxning** [comment]
After searching, i found that PR(#36) has successfully handle this problem. Maybe we can merge it. @cameronbwhite

**Comment by vanzhiganov** [comment]
I am fix this bug changing string no.127 in `routing.py` from:

        if "cas:memberOf" in attributes:

to

        if attributes and "cas:memberOf" in attributes:
