### ISSUE TITLE
None of the changes are fixing the issue for me. 

### ISSUE THREAD

**Issue by brdimattia** [cameronbwhite/Flask-CAS#37]
I've changed the routing file to the current version and still get this. 

Traceback (most recent call last):
  File "/Users/bookserve/Desktop/flask/lib/python3.4/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/bookserve/Desktop/flask/lib/python3.4/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/Users/bookserve/Desktop/flask/lib/python3.4/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/bookserve/Desktop/flask/lib/python3.4/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/Users/bookserve/Desktop/flask/lib/python3.4/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/bookserve/Desktop/flask/lib/python3.4/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/bookserve/Desktop/flask/lib/python3.4/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/bookserve/Desktop/flask/lib/python3.4/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/Users/bookserve/Desktop/flask/lib/python3.4/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/bookserve/Desktop/flask/lib/python3.4/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/bookserve/Desktop/flask/lib/python3.4/site-packages/Flask_CAS-1.0.1-py3.4.egg/flask_cas/routing.py", line 45, in login
    if validate(flask.session[cas_token_session_key]):
  File "/Users/bookserve/Desktop/flask/lib/python3.4/site-packages/Flask_CAS-1.0.1-py3.4.egg/flask_cas/routing.py", line 127, in validate
    if "cas:memberOf" in attributes:
TypeError: argument of type 'NoneType' is not iterable

**Comment by ericaroy** [comment]
Hi @brdimattia I am currently having this issue as well. Did you ever find a fix?
