### ISSUE TITLE
Exception if CAS server doesn't send attributes

### ISSUE THREAD

**Issue by RBukharov** [cameronbwhite/Flask-CAS#43]
Some servers are not send attributes. For example server I work with send the following xml after successful authentication:
```
 <cas:serviceResponse xmlns:cas='http://www.yale.edu/tp/cas'>
 	<cas:authenticationSuccess>
 		<cas:user>roman.bukharov</cas:user>
 
 	</cas:authenticationSuccess>
 </cas:serviceResponse>
```

In this case I have exception  below:
```
 Traceback (most recent call last):
   File "C:\Python35\lib\site-packages\flask\app.py", line 1817, in wsgi_app
     response = self.full_dispatch_request()
   File "C:\Python35\lib\site-packages\flask\app.py", line 1477, in full_dispatch_request
     rv = self.handle_user_exception(e)
   File "C:\Python35\lib\site-packages\flask_restful\__init__.py", line 271, in error_router
     return original_handler(e)
   File "C:\Python35\lib\site-packages\flask\app.py", line 1381, in handle_user_exception
     reraise(exc_type, exc_value, tb)
   File "C:\Python35\lib\site-packages\flask\_compat.py", line 33, in reraise
     raise value
   File "C:\Python35\lib\site-packages\flask\app.py", line 1475, in full_dispatch_request
     rv = self.dispatch_request()
   File "C:\Python35\lib\site-packages\flask\app.py", line 1461, in dispatch_request
     return self.view_functions[rule.endpoint](**req.view_args)
   File "C:\Python35\lib\site-packages\flask_cas\routing.py", line 45, in login
     if validate(flask.session[cas_token_session_key]):
   File "C:\Python35\lib\site-packages\flask_cas\routing.py", line 125, in validate
     attributes = xml_from_dict["cas:attributes"]
 KeyError: 'cas:attributes'
```
I think you should add a try/except block when parsing cas:attributes in the file `\lib\site-packages\flask_cas\routing.py` (line 125)

**Comment by MathieuDuponchelle** [comment]
Confirming, I had access to the CAS server I use for testing (django mama cas), and modified it to send the attributes, but obviously not everyone has that latitude

**Comment by jstevensfit** [comment]
If you don't need the attributes a temporary fix is to replace line 125 in `\lib\site-packages\flask_cas\routing.py` with:

`#attributes = xml_from_dict["cas:attributes"]
 attributes = ""
`

**Comment by pmayer** [comment]
Wouldn't be `attributes = xml_from_dict.get("cas:attributes", "")` better?

**Comment by RBukharov** [comment]
Solved: https://github.com/cameronbwhite/Flask-CAS/commit/a485e900f1d8bcabfa17d445ee38cb7abbf76247

**Comment by apulverizer** [comment]
I don't think that completely solves the issue. Our CAS server return an empty list of attributes which becomes None when parsed. So an additional check like this  is required:

```python
attributes = xml_from_dict.get("cas:attributes", {})
if attributes is None: attributes = {}
```

**Comment by pmayer** [comment]
Maybe it should be like this then?

```python
attributes = xml_from_dict.get("cas:attributes") or {}
```

**Comment by tiago-cruz-movile** [comment]
@RBukharov,

The commit https://github.com/cameronbwhite/Flask-CAS/commit/a485e900f1d8bcabfa17d445ee38cb7abbf76247 solved my problem, thanks!

Do you know when this release will be released to download with `pip`?

Thanks!!
