### ISSUE TITLE
what's the problem about"File "c:\python27\lib\site-packages\flask_cas\routing.py", line 125, in validate"

### ISSUE THREAD

**Issue by francisliyy** [cameronbwhite/Flask-CAS#45]
the error stack is below:
KeyError
KeyError: 'cas:attributes'

Traceback (most recent call last)
File "c:\python27\lib\site-packages\flask\app.py", line 2000, in __call__
return self.wsgi_app(environ, start_response)
File "c:\python27\lib\site-packages\flask\app.py", line 1991, in wsgi_app
response = self.make_response(self.handle_exception(e))
File "c:\python27\lib\site-packages\flask\app.py", line 1567, in handle_exception
reraise(exc_type, exc_value, tb)
File "c:\python27\lib\site-packages\flask\app.py", line 1988, in wsgi_app
response = self.full_dispatch_request()
File "c:\python27\lib\site-packages\flask\app.py", line 1641, in full_dispatch_request
rv = self.handle_user_exception(e)
File "c:\python27\lib\site-packages\flask\app.py", line 1544, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "c:\python27\lib\site-packages\flask\app.py", line 1639, in full_dispatch_request
rv = self.dispatch_request()
File "c:\python27\lib\site-packages\flask\app.py", line 1625, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
File "c:\python27\lib\site-packages\flask_cas\routing.py", line 45, in login
if validate(flask.session[cas_token_session_key]):
File "c:\python27\lib\site-packages\flask_cas\routing.py", line 125, in validate
attributes = xml_from_dict["cas:attributes"]
KeyError: 'cas:attributes'

**Comment by tiago-cruz-movile** [comment]
Looks the same as here https://github.com/cameronbwhite/Flask-CAS/issues/43
