### ISSUE TITLE
AttributeError: 'list' object has no attribute 'lstrip'

### ISSUE THREAD

**Issue by liudonghua123** [cameronbwhite/Flask-CAS#58]
It works for the standard [cas](https://github.com/apereo/cas) server, But when I use this perfect library to integrate to my ids server, it shown the following error.

```python
127.0.0.1 - - [09/May/2018 10:26:27] "GET /login/?ticket=ST-43153-EpldxJPeJzBJQWqwx2ih1525832788741-9WDe-ids1 HTTP/1.1" 500 -
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\flask\app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\ProgramData\Anaconda3\lib\site-packages\flask\app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "C:\ProgramData\Anaconda3\lib\site-packages\flask\app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\ProgramData\Anaconda3\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "C:\ProgramData\Anaconda3\lib\site-packages\flask\app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\ProgramData\Anaconda3\lib\site-packages\flask\app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\ProgramData\Anaconda3\lib\site-packages\flask\app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\ProgramData\Anaconda3\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "C:\ProgramData\Anaconda3\lib\site-packages\flask\app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\ProgramData\Anaconda3\lib\site-packages\flask\app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\ProgramData\Anaconda3\lib\site-packages\flask_cas\routing.py", line 45, in login
    if validate(flask.session[cas_token_session_key]):
  File "C:\ProgramData\Anaconda3\lib\site-packages\flask_cas\routing.py", line 128, in validate
    attributes["cas:memberOf"] = attributes["cas:memberOf"].lstrip('[').rstrip(']').split(',')
AttributeError: 'list' object has no attribute 'lstrip'
```

After going through the code, I find the error is this line `attributes["cas:memberOf"] = attributes["cas:memberOf"].lstrip('[').rstrip(']').split(',')`. The `attributes["cas:memberOf"]` is already a list object, no need to convert str to list.

So I change this line of code to
```python
if not isinstance(attributes["cas:memberOf"], list):
    attributes["cas:memberOf"] = attributes["cas:memberOf"].lstrip('[').rstrip(']').split(',')
```

Then it works.

**Comment by liudonghua123** [comment]
see this pr https://github.com/cameronbwhite/Flask-CAS/pull/59

**Comment by HadrienRenaud** [comment]
Is there any plan to merge this ? 
I have the same problem and I have to work with my own fork of this repo, which is a shame just for one line.

**Comment by liudonghua123** [comment]
@HadrienRenaud Hi, I updated the upstream code and make some changes better then the previous modifies. If you want to use this package immediately, add dependence in your requirements.txt as below.
```
git+https://github.com/liudonghua123/Flask-CAS.git@list_of_memberOf
```

**Comment by liudonghua123** [comment]
updated pr https://github.com/cameronbwhite/Flask-CAS/pull/78

**Comment by HadrienRenaud** [comment]
Thanks @liudonghua123 

Actually in my case in don't need all the post-processing for the `[` or `]` or `,` ([lines 138-141 of `routing.py`](https://github.com/cameronbwhite/Flask-CAS/blob/3d43b5147341f4d4def472efb0d879ac50ec4f32/flask_cas/routing.py#L138)), but it still works fine, so i think i will use it!
